### PR TITLE
Add SOAR-0007 proposal: Shorthand APIs for inputs and outputs

### PR DESCRIPTION
**Pull request by simonjbeaumont**
### Motivation

We'd like to run a proposal for generating additional API to simplify providing operation inputs and handling
operation outputs for simple API calls with just one successful outcome.

### Modifications

- Add SOAR-0007: Shorthand APIs for operation inputs and outputs

(See the proposal itself for details)[^1]

### Result

n/a

### Test Plan

n/a

### Related Issues

#22, #104, #105, #145

[^1]: https://github.com/apple/swift-openapi-generator/pull/291/files

### CODE REVIEW

**Comment by gjcairo** [comment]
This proposal is now **In Review**, which will run until September 29 - feel free to leave your feedback either on this PR or on the corresponding [Swift Forums post](https://forums.swift.org/t/proposal-soar-0007-shorthand-apis-for-inputs-and-outputs/67444).

Thanks @simonjbeaumont for the write-up!

**Comment by yanniks** [comment]
Also from my side, thank you for this proposal! I think it will really simplify many use-cases where the client component of the generator is used.
However, I'm wondering whether the thrown errors can be improved somehow. The challenge I see is that one might want to abstract error handling from the actual API call and catch `Unauthorized` or `Forbidden` responses in a certain way. With the current proposal, I don't see that there is a generic way of identifying whether the `UnexpectedResponseError` was thrown because of a `404`, `403` or a `400` HTTP status code response. Could this be incorporated in this draft somehow?

**Comment by MahdiBM** [comment]
Another related issue: https://github.com/apple/swift-openapi-generator/issues/145 🙂

**Comment by simonjbeaumont** [comment]
> Another related issue: #145 🙂

Thanks. I'd inconsistently referenced the issues between the proposal and the PR description 🤦 #145 was already referenced in the proposal itself, at least 🙂 

- Proposal: 22, 104, 145
- PR description: 22, 104, 105

I'll clean both up to be the union.

**Comment by simonjbeaumont** [comment]
> @simonjbeaumont did not really think of using a middleware. In that case, I really support this proposal. Thanks for detailed reply!

No problem!

**Comment by simonjbeaumont** [comment]
@swift-server-bot test this please

**Review by czechboy0 — APPROVED** [review]

**Pull request merged**
