### PR TITLE
Relax minimum macOS requirement to 10.15

### LINKED ISSUE #62: Support platform versions back to macOS 10.15,  iOS 13.0, tvOS 13.0, and watchOS 6.0
Let's see how much work it'd be to reduce the deployment targets, macOS 13->11, and so on.

This would be all of the repos - generator, runtime, and transports.

// Edit: Possibly we could go as low as `.macOS(.v10_15), .iOS(.v13), .tvOS(.v13), .watchOS(.v6)`.

### PR DESCRIPTION
**Pull request by andrewse02**
### Motivation

Reduce deployment target by 3 versions to gain more adoption.

### Modifications

- Reduced deployment targets by 3 versions
- Modified `client.Package.x` and `server.Package.x` files to reflect new deployment targets
- Modified documentation to reflect new deployment targets

### Result

Deployment target will be reduced by 3 versions and documentation will reflect such changes.

### Resolves

- Resolves #62

### Related PRs

- Paired with https://github.com/apple/swift-openapi-runtime/pull/18

### CODE REVIEW

**Review by czechboy0 — APPROVED** [review]

**Comment by czechboy0** [comment]
@swift-server-bot add to allowlist

**Review by czechboy0 — CHANGES_REQUESTED** [review]
Actually, please also update the README and Documentation.md with these new deployment versions.

**Comment by andrewse02** [comment]
Will do. Also noticed that the `client.Package.x` files' deployment targets can be reduced as well. Adding that too.

**Review by czechboy0 — APPROVED** [review]

**Review by czechboy0 — CHANGES_REQUESTED** [review]
Please also bump the dependency on the runtime library to 0.1.3, which also has the reduced versions.

**Comment by andrewse02** [comment]
@czechboy0 Sure! Just for future PRs, is that something I should have had in there from the start? Since this one was paired with a runtime PR should I have known to increase the version number based on the `semver/X` label?

**Comment by simonjbeaumont** [comment]
> Just for future PRs, is that something I should have had in there from the start? Since this one was paired with a runtime PR should I have known to increase the version number based on the `semver/X` label?

Assuming you mean the bumping of the runtime dependency version, then you couldn't have done it from the start because we needed to publish the release first, so you didn't miss any steps :)

It's masked because the dependency on the runtime is only consumed in a test target within the generator, but if it was consumed in a library or executable target then the CI would have failed.

We're just wanting to make sure we do a coordinated rollout in this instance.

As to whether you'll need to always bump the version of the runtime library: not really, it depends on the change.

Thanks for your contribution!

**Review by czechboy0 — APPROVED** [review]

**Review by simonjbeaumont — APPROVED** [review]

**Pull request merged**
