### PR TITLE
Fix warning in generated server code

### PR DESCRIPTION
**Pull request by arthurcro**
### Motivation

Fixes https://github.com/apple/swift-openapi-generator/issues/190.
 
### Modifications

We fix the issue buy only generating this initializer if there's at least one operation. Otherwise keep the method empty.

### Result

The warning is fixed since the `server` variable declaration is not added to the `registerHandlers` body when it's not used. 

### Test Plan

We add a test in `SnippetBasedReferenceTests.swift` called `testServerRegisterHandlers_noOperations` asserting the `server` variable delcaration is not added to the `registerHandlers` body.

### CODE REVIEW

**Comment by arthurcro** [comment]
Hey @czechboy0! I'm not sure where to add a proper test for this, do you have any idea how I could write a good test for this scenario? 🙂

**Comment by czechboy0** [comment]
Sure - using a snippet test would be ideal. But I'll have to create a new util function for it, let me push it directly into your branch, will let you know when it's ready.

**Comment by czechboy0** [comment]
@arthurcro here you go: https://github.com/apple/swift-openapi-generator/pull/209/commits/2faf80427ef0dcd3c3ee854ed1ab6a74804e66e0

I created a test called `testServerRegisterHandlers_oneOperation`. I'll leave it as an exercise to you to create `testServerRegisterHandlers_noOperations` 🙂

**Comment by arthurcro** [comment]
That's aweomse @czechboy0, thank you so much! I'll add the missing test as soon as possible and mark the PR as ready! 🙂

**Review by czechboy0 — APPROVED** [review]
Great, thank you!

**Pull request merged**
