### PR TITLE
Support base64-encoded data

### PR DESCRIPTION
**Pull request by rnro**
This change accompanies https://github.com/apple/swift-openapi-runtime/pull/55 and relies on it for the `OpenAPIRuntime.Base64EncodedData` type.

### Motivation

OpenAPI supports base64-encoded data but to this point Swift OpenAPI Generator has not (https://github.com/apple/swift-openapi-generator/issues/11).

### Modifications

A data type specified as `type: string, format: byte` will now result in a generated type which is `Codable` and backed by a `OpenAPIRuntime.Base64EncodedData` type which knows how to encode and decode base64 data.

### Result

Users will be able to specify request/response payloads as base64-encoded data which will be encoded and decoded transparently

### Test Plan

Unit tested locally.

### CODE REVIEW

**Comment by czechboy0** [comment]
@swift-server-bot add to allowlist

**Comment by czechboy0** [comment]
@rnro As a last thing, can you add a base64 property to an object of your choice in the file-based reference tests? I'm a little paranoid that this PR is _passing_ even though we haven't released the update runtime yet, which means we're not testing that it all builds and works together. Add a property, and make sure PetstoreConsumerTests are updated to also populate and verify the value both on client and server side. Otherwise lgtm.

**Comment by rnro** [comment]
Thanks for the review, I've added an endpoint to upload audio of your pet in base64-encoded binary format. I'm not sure if that's the best API design for an actual pet app but I think it's plausible to get the new code in there.

**Review by czechboy0 — CHANGES_REQUESTED** [review]
Please also add tests to Test_Client and Test_Server that set and verify the value in `Pet.genome`, just to make sure it works end-to-end.

**Comment by czechboy0** [comment]
Also, you can now update to 0.3.2 of the runtime library in Package.swift of swift-openapi-generator, all that should hopefully make the CI green on this PR.

**Pull request merged**
