### PR TITLE
Add test for OperationDescription.responseOutcomes

### PR DESCRIPTION
**Pull request by mt-hodaka**
### Motivation

I couldn't reproduce the issue #530 on my end.
However, I noticed that there were no tests, so I would like to add them.

### Modifications

Adding tests.

### Result

Only adding tests, no change in the behavior of the library.

### Test Plan

Added tests are passing.

### CODE REVIEW

**Comment by simonjbeaumont** [comment]
@swift-server-bot test this please

**Comment by simonjbeaumont** [comment]
Weird, we're getting a bunch of failures in our compat suite now, but there's been no change to the project or the OpenAPI documents (which are referenced by Git hash). I wonder if this has been caused by a dependency change somewhere. Possibly related to the discussion going on in https://github.com/apple/swift-openapi-generator/issues/553.

Have opened an empty PR to isolate: https://github.com/apple/swift-openapi-generator/pull/555.

//cc @czechboy0

**Comment by czechboy0** [comment]
@swift-server-bot test this please

**Comment by czechboy0** [comment]
@swift-server-bot test this please

**Pull request merged**
