### PR TITLE
docs: Update instructions for running developer scripts

### LINKED ISSUE #79: Script to generate the contributor list has incorrect documentation
In `generate-contributors-list.sh` file, it is suggesting we run `./scripts/generate-contributors-list.sh` to update CONTRIBUTORS.txt. However this file is not executable

```
Please do not edit this file manually. It is generated using \`./scripts/generate-contributors-list.sh\`. If a name is misspelled or appearing multiple times: add an entry in \`./.mailmap\`
```

```shell
➜  swift-openapi-generator git:(main) l scripts             
total 72
drwxr-xr-x  11 kyle  staff   352B  6 20 11:38 .
drwxr-xr-x@ 27 kyle  staff   864B  6 20 11:38 ..
-rw-r--r--   1 kyle  staff   1.2K  6 19 23:50 check-for-broken-symlinks.sh
-rw-r--r--   1 kyle  staff   1.3K  6 19 23:50 check-for-docc-warnings.sh
-rw-r--r--   1 kyle  staff   1.3K  6 19 23:50 check-for-unacceptable-language.sh
-rw-r--r--   1 kyle  staff   3.7K  6 20 11:38 check-license-headers.sh
-rw-r--r--   1 kyle  staff   1.9K  6 19 23:50 generate-contributors-list.sh
-rw-r--r--   1 kyle  staff   2.2K  6 19 23:50 run-integration-test.sh
-rw-r--r--   1 kyle  staff   1.5K  6 20 11:38 run-swift-format.sh
-rwxr-xr-x   1 kyle  staff   1.4K  6 19 23:50 soundness.sh
-rw-r--r--   1 kyle  staff   106B  6 19 23:50 unacceptable-language.txt
```

Since all the scripts file already have `#!` in the header, we should consider add executable permission to them by `chmod +x scripts/*.sh`

### PR DESCRIPTION
**Pull request by Kyle-Ye**
### Motivation

close #79

### Modifications

Update script permission

### CODE REVIEW

**Review by czechboy0 — CHANGES_REQUESTED** [review]
Ah good catch - we intentionally wanted to avoid the individual scripts being executable, so this is intentional. Can you instead update the docs to say that one should run it as `bash ./scripts/...` please?

**Comment by Kyle-Ye** [comment]
> Ah good catch - we intentionally wanted to avoid the individual scripts being executable, so this is intentional. Can you instead update the docs to say that one should run it as `bash ./scripts/...` please?

Got it. In that case can we consider only adding executable permission to `generate-contributors-list.sh` instead of updating docs.

Expected Result
```
total 72
drwxr-xr-x  11 kyle  staff   352B  6 20 13:18 .
drwxr-xr-x@ 27 kyle  staff   864B  6 20 13:18 ..
-rw-r--r--   1 kyle  staff   1.2K  6 20 13:18 check-for-broken-symlinks.sh
-rw-r--r--   1 kyle  staff   1.3K  6 20 13:18 check-for-docc-warnings.sh
-rw-r--r--   1 kyle  staff   1.3K  6 20 13:18 check-for-unacceptable-language.sh
-rw-r--r--   1 kyle  staff   3.7K  6 20 13:18 check-license-headers.sh
-rwxr-xr-x   1 kyle  staff   1.9K  6 20 13:19 generate-contributors-list.sh
-rw-r--r--   1 kyle  staff   2.2K  6 20 13:18 run-integration-test.sh
-rw-r--r--   1 kyle  staff   1.5K  6 20 13:18 run-swift-format.sh
-rwxr-xr-x   1 kyle  staff   1.4K  6 19 23:50 soundness.sh
-rw-r--r--   1 kyle  staff   106B  6 19 23:50 unacceptable-language.txt
```

**Comment by czechboy0** [comment]
No, I think what you have in the PR now is good - just update the docs, without adding executable permissions to additional files.

**Review by czechboy0 — APPROVED** [review]

**Comment by czechboy0** [comment]
@swift-server-bot add to allowlist

**Comment by Kyle-Ye** [comment]
> No, I think what you have in the PR now is good - just update the docs, without adding executable permissions to additional files.

Got it.

**Review by simonjbeaumont — APPROVED** [review]

**Pull request merged**
