### PR TITLE
Docs: Change macos platform version

### PR DESCRIPTION
**Pull request by abdulajet**
### Motivation

I was following the tutorial, but it was unable to build due to `OpenAPIVapor` requiring a higher minimum target

Screenshot 2023-07-06 at 09 39 59

### Modifications

I changed the version of macOS in the "Generating server stubs in a Swift package" tutorial.

### Result

You should be able to follow the tutorial all the way through without errors

### Test Plan

Ran the soundness script.

### CODE REVIEW

**Comment by czechboy0** [comment]
We reduced the deployment target in the last release, I wonder if Vapor's transport package could do the same, we could support 10.15 in the tutorial still? cc @0xTim for thoughts?

**Comment by 0xTim** [comment]
@czechboy0 @abdulajet done! If you do a package update it should work

**Comment by simonjbeaumont** [comment]
Thanks @0xTim for the quick turnaround.

@abdulajet I'll close this PR, as we deliberately lowered the version. Could you confirm that you are now unblocked once you update to the latest version of swift-openapi-vapor and, if you still have any problem, open an issue and we'll happily take a look.

**Comment by abdulajet** [comment]
@0xTim @simonjbeaumont @czechboy0 Nice one, thanks.

**Pull request closed without merging**
